# Generated by Django 5.1.6 on 2025-04-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_movie_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdbRating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.TextField(),
        ),
    ]
