# Generated by Django 5.1.6 on 2025-04-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_imdbrating_alter_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.TextField(max_length=5),
        ),
    ]
