# Generated by Django 5.1.6 on 2025-03-11 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together={("user", "name")},
        ),
    ]
