# Generated by Django 5.1.6 on 2025-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
    ]
