# Generated by Django 5.1.6 on 2025-04-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
        ("movies", "0004_alter_movie_rating"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("profile", "movie")},
        ),
    ]
