# Generated by Django 5.1.6 on 2025-04-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
